"""added new fields amoutpaid ,paymentstatus 

Revision ID: 077ecc696d19
Revises: 47a55507e053
Create Date: 2025-06-14 11:30:38.919149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077ecc696d19'
down_revision = '47a55507e053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('vehicle_number')

    # ### end Alembic commands ###
