"""added is_rating

Revision ID: 119eb341fc0d
Revises: 077ecc696d19
Create Date: 2025-07-13 23:49:04.946952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119eb341fc0d'
down_revision = '077ecc696d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.drop_column('is_rated')

    # ### end Alembic commands ###
