"""changed pincodes to str datatype

Revision ID: 47a55507e053
Revises: 90807f920e11
Create Date: 2025-06-13 21:10:33.272769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a55507e053'
down_revision = '90807f920e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('lot_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('reserve_parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('lot_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
