"""is_active to parkingLot

Revision ID: 4c375ea628e3
Revises: db056c84e336
Create Date: 2025-06-13 19:08:36.247732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c375ea628e3'
down_revision = 'db056c84e336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
