"""changed int to str in parkingspot

Revision ID: 90807f920e11
Revises: 13a41cada3bf
Create Date: 2025-06-13 19:38:24.505153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90807f920e11'
down_revision = '13a41cada3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
